insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado, Alumno_idAlumno, Carrera_idCarrera) values (1, 1, true, 2010,1,5);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (2, 2, false,null,1,3);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (3, 3, true, 2011,2,1);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (4, 4, true, 1984,2,4);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (5, 5, true, 2012,3,1);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (6, 6, false, null,4,1);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (7, 7, true, 1991,5,5);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (8, 8, false, null, 6,2);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (9, 9, true, 1992,7,4);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (10, 10, false, null, 8,2);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (11, 11, false, null, 9,1);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (12, 12, false, null, 10,2);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (13, 13, true, 2015, 10,4);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (14, 14, false, null, 10, 5);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (15, 15, true, 1996, 11, 1);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (16, 16, true, 2006,11,5);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (17, 17, true, 2008,12,2);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (18, 18, false, null,12,1);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (19, 19, true, 1997,13,5);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (20, 20, false, null, 14,4);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (21, 21, false, null, 15,1);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (22, 22, true, 2010, 15,2);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (23, 23, false, null,16,2);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (24, 24, false, null, 17,3);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (25, 25, false, null,18,3);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (26, 26, false, null, 19,4);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (27, 27, true, 2009, 19,5);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (28, 28, true, 1995,20, 1);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (29, 29, true, 2000, 21,5);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (30, 30, true, 2001, 22, 1);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (31, 31, true, 2006, 23, 5);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (32, 32, true, 1993, 24, 4);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (33, 33, true, 1998, 25, 3);
insert into Carrera_inscripta (id, antiguedad, graduado, anio_graduado,Alumno_idAlumno, Carrera_idCarrera) values (34, 34, false, null, 5, 4);
